# .github/workflows/ci.yml

name: Run Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Add this 'services' block to start a PostgreSQL container
    services:
      postgres:
        image: postgres:13 # Use a specific postgres version
        # Set database user, password, and name
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: testdb
        # Health check to ensure the database is ready before tests run
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432 # Map the container's port to the host

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add psycopg2-binary here to ensure the postgres driver is installed
        pip install psycopg2-binary
        # FIX: Remove Windows-specific dependencies before installing
        # This command finds the line with 'pywin32' and deletes it.
        sed -i '/pywin32/d' back/requirements.txt
        pip install -r back/requirements.txt

    - name: Run Pytest
      env:
        # Update DATABASE_URL to connect to the service container
        # Note: The hostname is 'postgres' because it matches the service name
        DATABASE_URL: postgresql://postgres:password123@localhost:5432/testdb
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        cd back
        pytest