# .github/workflows/ci.yml

name: Run Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary
        
        # FIX: Use grep to robustly remove the Windows-specific dependency.
        # This creates a new file without the pywin32 line, then replaces the old one.
        grep -v "pywin32" back/requirements.txt > back/requirements.txt.tmp && mv back/requirements.txt.tmp back/requirements.txt
        
        pip install -r back/requirements.txt

    - name: Run Pytest
      env:
        DATABASE_URL: postgresql://postgres:password123@localhost:5432/testdb
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        cd back
        pytest